#-------------------------------
# General Site Settings
title: CaliforniaLuv
logo: logo.png # You can add own logo.
description: CaliforniaLuv is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Lee Jin-Sung
  image: 01.jpg
  say-hello: Hello, I’m <strong>Lee Jin-Sung</strong>
  bio: I am a  <strong>front-end developer</strong>, and I am in charge of  <strong>web</strong> development. I always consider UX UI to be important in my project.


#-------------------------------
# Contact links
instagram: https://www.instagram.com/chewbacca.96/ # Add your Instagram handle
github: https://github.com/CaliforniaLuv

#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
